import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import Header from "@/components/Header";
import { ThemeProvider } from "@/components/theme-provider"
import BackHome from "@/components/BackHome";

export const metadata: Metadata = {
  title: "James Jimenez",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="scroll-smooth " lang="en">
      <head>
        {/* Prevent theme mismatch on first load */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              try {
                localStorage.setItem('theme', 'light');
                document.documentElement.classList.remove('dark');
                document.documentElement.classList.add('light');
              } catch (e) {}
            `,
          }}
        />
      </head>
      <body
        className={`antialiased ${poppins.className} px-10 `}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem={false}
          storageKey="theme"
          themes={["light", "dark"]}
          disableTransitionOnChange
        >
          <BackHome />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
